{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cnj-persistence-sql-backend-micro.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "cnj-persistence-sql-backend-micro.name" . }}
    helm.sh/chart: {{ include "cnj-persistence-sql-backend-micro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
{{- if empty .Values.ingress.host }}
    - http:
        paths:
  {{- if empty .paths }}
        - path: "/{{ $fullName }}"
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
  {{- else }}
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
        {{- end }}
  {{- end }}
{{- else }}
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
