# Default values for cnj-persistence-sql-backend-spring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.at.automotive.msg.team/cloudtrain/cnj-persistence-sql-backend-spring
  tag: latest
  pullPolicy: Always

probes:
  readiness:
    path: /actuator/health
  liveness:
    path: /actuator/health

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  hosts:
    - host: ""
      paths: []
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# security configuration (MP JWT AUTH)

# database configuration
database:
  postgres:
    name: cloudtrain
    host: cnj-persistence-sql-database-postgresql
    port: 5432
    secret:
      name: cnj-persistence-sql-database-postgresql
      keys:
        user: postgresql-username
        password: postgresql-password
