# Default values for cnj-persistence-sql-backend-javaee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ${docker.image.name}
  tag: ${project.version}
  pullPolicy: IfNotPresent

probes:
  readiness:
    path: /api/v1/probes/readiness
  liveness:
    path: /api/v1/probes/liveness

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "${k8s.ingress.host}"
      paths: ["${k8s.ingress.path}"]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 756Mi

# security configuration (MP JWT AUTH)
mp:
  jwt:
    verifyPublicKeyLocation: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain/protocol/openid-connect/certs"
    verifyIssuer: "https://iam.at41tools.k8s.aws.msgoat.eu/auth/realms/cloudtrain"

# database configuration
database:
  postgres:
    user: postgres
    database: cloudtrain
    host: cnj-persistence-sql-resources-postgresql
    port: 5432
    secret:
      name: cnj-persistence-sql-resources-postgresql
      keys:
        password: postgresql-password
